name: pixovo_mobile
description: Pixovo - Create beautiful photo books and print products.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6

  # State Management
  flutter_riverpod: ^2.5.1
  riverpod_annotation: ^2.3.5

  # Networking
  dio: ^5.4.3+1

  # Routing
  go_router: ^14.2.0

  # Storage
  flutter_secure_storage: ^9.2.2
  shared_preferences: ^2.2.3

  # Image Handling
  image_picker: ^1.1.2
  cached_network_image: ^3.3.1
  image_cropper: ^7.1.0

  # UI
  google_fonts: ^6.2.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.10+1
  lottie: ^3.1.2

  # Utilities
  intl: ^0.20.2
  uuid: ^4.4.0
  flutter_animate: ^4.5.0
  
  # Integrations
  google_sign_in: ^6.2.1
  flutter_facebook_auth: ^7.0.0
  pay: ^2.0.0
  flutter_credit_card: ^4.0.1
  flutter_colorpicker: ^1.1.0
  url_launcher: ^6.2.6
  share_plus: ^9.0.0
  path_provider: ^2.1.3
  font_awesome_flutter: ^10.7.0
  matrix_gesture_detector: any
  photo_manager: ^3.0.0-dev.5
  flutter_paypal_payment: any

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  riverpod_generator: ^2.4.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/animations/
    - assets/fonts/
